name: SSM-CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Setup Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.9.3'
        
    - name: Install dependencies
      run: |
        julia --project -e 'using Pkg; Pkg.instantiate()'

    - name: Run tests with coverage
      run: |
        julia --project="$GITHUB_WORKSPACE" -e 'using Pkg; Pkg.test("SSM", coverage=true)'

    - name: Upload coverage reports to Codecov
      uses: julia-actions/julia-processcoverage@v1
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
